oe-meta-go: revert to commit a15be494
meta-resin/meta-resin-common/recipes-devtools/go-cross/go_1.7.3.inc
requires go-common.inc (and subsequent dependencies) which is currently
provided by oe-meta-go submodule.

oe-meta-go repository re-organized go recipes in
https://github.com/mem/oe-meta-go/commit/6882ae820f59571c4c99204e92a921b3a4e1cf1c

As a result, go-common.inc and its dependencies aren't available from the
above commit and will break meta-resin recipe as soon as oe-meta-go is
updated to later versions:
ERROR: ParseError at
meta-resin/meta-resin-common/recipes-devtools/go-cross/go_1.7.3.inc:1:
Could not include required file recipes-devtools/go/go-common.inc

Stick to oe-meta-go revision a15be494a64c36fd7dc4d1808c9d13d0fbee56bf

Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>